const WORDS = [
  'I love you most.',
  "You're the best cook.",
  'I love your genius, amazing brain.',
  "You're the most hardworking person I know.",
  "I'm so proud to be your partner.",
  'You make every day brighter.',
  'Your smile is my favorite sight.',
  'I believe in you completely.',
  'You are breathtaking inside and out.',
  'You make our house a home.',
  "I'm grateful for you every single day.",
  'Your kindness inspires me.',
  'You are my safest place.',
  "I'm amazed by your strength.",
  'You make me want to be better.',
  'Your laugh is my favorite sound.',
  'I trust your judgment.',
  'You are irreplaceable.',
  'Thank you for loving me so well.',
  "You're my favorite person to do life with.",
  'Your heart is pure gold.',
  'I appreciate all the little things you do.',
  'You handle challenges with such grace.',
  "I'm in awe of your creativity.",
  "You're an incredible listener.",
  'You make everyone around you feel valued.',
  'Your ideas are brilliant.',
  'I love how thoughtful you are.',
  'You have a gift for seeing the good.',
  'I love the way you love our family.',
  'You are my best friend.',
  'You make ordinary moments magical.',
  'Your perseverance is inspiring.',
  'You are more than enough.',
  'I love the way your mind works.',
  "You're gorgeous—today and every day.",
  'I admire your integrity.',
  "I'm grateful for your patience.",
  'You bring out the best in me.',
  "You're a wonderful example to others.",
  'I cherish our time together.',
  "I'm thankful for your honesty.",
  'You are my favorite hello and hardest goodbye.',
  'You make me feel seen and heard.',
  'Your confidence is attractive.',
  'You are a masterpiece.',
  'You are so loved—by me and so many.',
  "You're my sunshine on a cloudy day.",
  'I love your sense of humor.',
  'You always know how to make me smile.',
  'Your hugs feel like home.',
  "You're doing an amazing job.",
  "I'm lucky to love you.",
  'You have incredible wisdom.',
  'Your courage is beautiful.',
  'You handle pressure like a pro.',
  'You bring peace to my life.',
  'You are my favorite adventure.',
  'I love how you notice the details.',
  'You make difficult things look easy.',
  'Your voice is my favorite sound.',
  "You're radiant.",
  "You're my miracle.",
  'I admire your dedication.',
  'You are a blessing.',
  'You make me proud every day.',
  'You glow with kindness.',
  'Your empathy is a superpower.',
  "You're the calm in my storm.",
  "I'm grateful for your support.",
  "You're the best partner I could ask for.",
  'Your love is my greatest gift.',
  "I'm thankful for your sacrifices.",
  'You inspire me to dream bigger.',
  "You're wonderful just as you are.",
  'I love how you care so deeply.',
  'You are an answered prayer.',
  'You make me feel lucky every day.',
  "You're a natural leader.",
  "You never give up—it's amazing.",
  "You're incredibly talented.",
  'I admire your work ethic.',
  'You are my favorite thought.',
  "I'm better because of you.",
  'Your smile lights up the room.',
  "You're my home.",
  'You are so thoughtful and generous.',
  'I love how you always find a way.',
  "You're a phenomenal woman.",
  "You're my greatest joy.",
  'You handle change with grace.',
  "You're my person, forever.",
  'You deserve all the good things.',
  "I'm grateful for your perspective.",
  "You're beautiful when you're focused.",
  "You're beautiful when you're relaxed.",
  "You're beautiful when you're you.",
  'Your faithfulness means everything to me.',
  "You're my constant.",
  'You bring warmth wherever you go.',
  "You're my favorite blessing.",
  'You make me feel loved in every way.',
  'I admire your kindness to strangers.',
  'You are incredibly capable.',
  'You make me feel safe.',
  "You're the heart of our family.",
  "You're a fantastic friend.",
  "I love the life we're building.",
  'You turn challenges into opportunities.',
  "You're my daily reminder of love.",
  "I'm grateful for your laughter.",
  "You're my greatest cheerleader.",
  "You're the best decision I ever made.",
  'I love the way you think.',
  "You're wonderfully unique.",
  "You're my favorite teammate.",
  'Your patience amazes me.',
  'You deserve to be celebrated.',
  'You bring out my courage.',
  'You are the love of my life.',
  'I love your adventurous spirit.',
  "You're a light to everyone around you.",
  'I appreciate your attention to detail.',
  "You're incredibly resourceful.",
  "I'm grateful for your resilience.",
  'You make the world better.',
  "You're my confidant.",
  "You're the best part of my day.",
  'Your warmth fills our home.',
  'I appreciate your honesty and openness.',
  'You bring joy to my heart.',
  'You amaze me every day.',
  'I love your gentle strength.',
  "You're the definition of grace.",
  'You are thoughtful and wise.',
  "You're so fun to be around.",
  'I admire your independence.',
  'Your presence is comforting.',
  'You make me feel cherished.',
  'I appreciate how you show love.',
  "You're steady and strong.",
  "You're my favorite story.",
  "You're a dream come true.",
  'You make me feel lucky beyond words.',
  "You're magnetic.",
  "You're unforgettable.",
  "I'm grateful for your courage to be you.",
  'You make love feel easy.',
  "You're my inspiration.",
  "You're a wonder.",
  'Your heart makes everything better.',
  "You're my greatest gift.",
  "I'll always choose you.",
  "You're my forever love.",
  'I admire your curiosity.',
  'You think so deeply and beautifully.',
  "You're a brilliant problem-solver.",
  "You're a phenomenal partner in every way.",
  "You're generous with your love.",
  'I appreciate your transparency.',
  "You're compassionate and brave.",
  'You carry yourself with elegance.',
  "You're my favorite companion.",
  'Your tenderness moves me.',
  'You make hard days bearable.',
  'You brighten my mornings.',
  'You soothe my evenings.',
  "You're my favorite goodnight.",
  'Your calm steadies me.',
  "You're a treasure.",
  "You're dazzling.",
  "You're my safe harbor.",
  "You're my biggest blessing.",
  'You are deeply appreciated.',
  "You're the best part of me.",
  'You make me laugh like no one else.',
  'You are a joy to love.',
  "You're remarkably insightful.",
  "You're my constant encouragement.",
  "You're a beautiful soul.",
  "You're my heart's home.",
  "You're endlessly interesting to me.",
  "You're my favorite conversation.",
  'You make life sweeter.',
  "You're the love I prayed for.",
  'You amaze me with your compassion.',
  "You're my anchor.",
  "You're my light.",
  "You're a gift I'll never take for granted.",
  'I love your adventurous heart.',
  "I'm grateful for your gentle wisdom.",
  "You're radiant when you're passionate.",
  'You make me feel important.',
  'I love how you encourage me.',
  "You're steady when I'm not.",
  "I'm thankful for your partnership.",
  "You're the best teammate in life.",
  'You are so dependable.',
  'Your joy is contagious.',
  "You're my favorite encourager.",
  'You pour love into everything you do.',
  'You are such a comfort to me.',
  "You're a phenomenal mom (and an even better partner).",
  "You're my favorite surprise.",
  "You're my everyday miracle.",
  "You're so good to me.",
  "You're my forever and always.",
  "You're unstoppable when you set your mind to something.",
  "You're my favorite yes.",
  'You make me feel chosen.',
  "You're the best part of my future.",
  "You're thoughtful beyond measure.",
  "You're my peace.",
  "You're beautifully authentic.",
  'You bring meaning to my life.',
  "You're my happy place.",
  "You're strong and soft in perfect balance.",
  "You're my favorite blessing to count.",
  "You're so fun to love.",
  "You're the queen of my heart.",
  'You amaze me with your focus.',
  "You're radiant when you're yourself.",
  "You're my greatest adventure and my calm.",
  "You're my favorite tradition.",
  'You make me feel lucky to be me.',
  "You're brilliant at what you do.",
  "You're an extraordinary woman.",
  "You're the best thing that ever happened to me.",
  "You're my partner in all things.",
  "You're a masterpiece I get to admire forever.",
  "You're beautiful in every season.",
  "You're so good at loving people.",
  "You're my favorite thought to wake up to.",
  "You're my favorite reason to hurry home.",
  'You make love feel brand new.',
  "You're enough—more than enough.",
  "You're my always.",
];

export function displayWords() {
  const i = Math.floor(Math.random() * WORDS.length);
  document.getElementById('out').textContent = WORDS[i];
}
